### ISSUE TITLE
Plan and Create a Performance Test Environment using the specs provided

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-performance-tests#18]
Create a docker image that is able to connect to the ICAP client & run the Jmeter script

**Comment by dpatel7** [comment]
Resource | Platform | Nbr of Nodes | CPU/node | OS | Memory | Storage
-- | -- | -- | -- | -- | -- | --
Azure Container Service | K8 Cluster | 3 | 2 vcpus | Linux | 7GiB | TBC
